# 结果保存的目录名称
result_name: demo_test

# 预训练模型检查点路径
continue_ckpt: model/model.ckpt

# 三平面低分辨率通道数
triplane_channels_low: 128
# 三平面高分辨率通道数
triplane_channels_high: 512
# 三平面分辨率
triplane_resolution: 128

# 每个面采样的点数
n_point_per_face: 1000
# 每批次处理的最大顶点数
n_sample_each: 10000
# 是否为点云输入(否则为网格)
is_pc : False
# 是否使用重网格化演示模式
remesh_demo : False

dataset:
  # 数据集类型
  type: "Mix"
  # 数据路径，指向包含所有3D模型的目录
  data_path: "objaverse_data"
  # 训练批大小
  train_batch_size: 1
  # 验证批大小
  val_batch_size: 1
  # 训练数据加载线程数
  train_num_workers: 8

loss:
  # 三元组损失权重
  triplet: 1.0

# 是否使用2D特征
use_2d_feat: False
# PVCNN模型配置
pvcnn:
  # 点编码器类型
  point_encoder_type: 'pvcnn'
  # 三平面通道数
  z_triplane_channels: 256
  # 三平面分辨率
  z_triplane_resolution: 128