// Auto-generated by scan_urdf.py
export const initialModels = [
    {
        "urdf": "../../urdf/7128/mobility.urdf",
        "meta": "../../urdf/7128/meta.json",
        "color": "#263238"
    },
    {
        "urdf": "../../urdf/900000/mobility.urdf",
        "meta": "../../urdf/900000/meta.json",
        "color": "#263238"
    }
];
